# -*- coding: utf-8 -*-
"""Suha Al- Task: third

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fuN0pcJnaOHnXTMPSfpQ8Wu9ARvZxDn

**Adapter pattern**
"""

// Existing (incompatible) interface
class LegacyPrinter {
    public void printText(String text) {
        System.out.println("Legacy printing: " + text);
    }
}

// Target interface expected by new client code
interface Printer {
    void print(String message);
}

// Adapter: makes LegacyPrinter compatible with Printer
class LegacyPrinterAdapter implements Printer {
    private final LegacyPrinter legacyPrinter;

    public LegacyPrinterAdapter(LegacyPrinter legacyPrinter) {
        this.legacyPrinter = legacyPrinter;
    }

    @Override
    public void print(String message) {
        legacyPrinter.printText(message); // delegate call
    }
}

// Client/demo
public class AdapterDemo {
    public static void main(String[] args) {
        LegacyPrinter legacy = new LegacyPrinter();
        Printer printer = new LegacyPrinterAdapter(legacy);
        printer.print("Hello Adapter Pattern!");
    }
}

"""**Facade pattern**"""

// Subsystem classes
class AudioPlayer {
    void loadFile(String file) { System.out.println("Audio loaded: " + file); }
    void play() { System.out.println("Audio playing"); }
}

class VideoPlayer {
    void loadStream(String url) { System.out.println("Video stream: " + url); }
    void start() { System.out.println("Video playing"); }
}

class SubtitleService {
    void loadSubtitles(String file) { System.out.println("Subtitles: " + file); }
}

// Facade
class MediaFacade {
    private final AudioPlayer audio = new AudioPlayer();
    private final VideoPlayer video = new VideoPlayer();
    private final SubtitleService subs = new SubtitleService();

    public void playMovie(String videoUrl, String subtitleFile) {
        video.loadStream(videoUrl);
        subs.loadSubtitles(subtitleFile);
        video.start();
    }

    public void playSong(String audioFile) {
        audio.loadFile(audioFile);
        audio.play();
    }
}

// Client/demo
public class FacadeDemo {
    public static void main(String[] args) {
        MediaFacade player = new MediaFacade();
        player.playSong("track.mp3");
        player.playMovie("http://movie", "movie.srt");
    }
}

"""**Composite pattern**"""

import java.util.ArrayList;
import java.util.List;

// Component
interface FileSystemItem {
    void show(int indent);
}

// Leaf
class FileItem implements FileSystemItem {
    private final String name;

    public FileItem(String name) {
        this.name = name;
    }

    @Override
    public void show(int indent) {
        System.out.println(" ".repeat(indent) + "- File: " + name);
    }
}

// Composite
class Directory implements FileSystemItem {
    private final String name;
    private final List<FileSystemItem> children = new ArrayList<>();

    public Directory(String name) {
        this.name = name;
    }

    public void add(FileSystemItem item) {
        children.add(item);
    }

    @Override
    public void show(int indent) {
        System.out.println(" ".repeat(indent) + "+ Dir: " + name);
        for (FileSystemItem child : children) {
            child.show(indent + 2);
        }
    }
}

// Client/demo
public class CompositeDemo {
    public static void main(String[] args) {
        Directory root = new Directory("root");
        Directory src = new Directory("src");
        Directory res = new Directory("resources");

        src.add(new FileItem("Main.java"));
        src.add(new FileItem("Utils.java"));
        res.add(new FileItem("config.yml"));

        root.add(src);
        root.add(res);

        root.show(0);
    }
}

"""**Decorator pattern**"""

// Component
interface Notifier {
    void send(String message);
}

// Concrete component
class EmailNotifier implements Notifier {
    @Override
    public void send(String message) {
        System.out.println("Email: " + message);
    }
}

// Base decorator
abstract class NotifierDecorator implements Notifier {
    protected final Notifier wrappee;

    protected NotifierDecorator(Notifier wrappee) {
        this.wrappee = wrappee;
    }

    @Override
    public void send(String message) {
        wrappee.send(message);
    }
}

// Concrete decorators
class SMSNotifier extends NotifierDecorator {
    public SMSNotifier(Notifier wrappee) {
        super(wrappee);
    }

    @Override
    public void send(String message) {
        super.send(message);
        System.out.println("SMS: " + message);
    }
}

class SlackNotifier extends NotifierDecorator {
    public SlackNotifier(Notifier wrappee) {
        super(wrappee);
    }

    @Override
    public void send(String message) {
        super.send(message);
        System.out.println("Slack: " + message);
    }
}

// Client/demo
public class DecoratorDemo {
    public static void main(String[] args) {
        Notifier notifier =
            new SlackNotifier(
                new SMSNotifier(
                    new EmailNotifier()));

        notifier.send("Build finished.");
    }
}